/*
 * File:           E:\Documents\DIY Bluetooth Speakers\DSP\Custom_Config\SigmaStudio_project\Export\0_template_IC_1_PARAM.h
 *
 * Created:        Saturday, October 19, 2024 2:20:11 PM
 * Description:    0_template:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __0_TEMPLATE_IC_1_PARAM_H__
#define __0_TEMPLATE_IC_1_PARAM_H__


/* Module S Splitter1_2 - Single Control Splitter*/
#define MOD_SSPLITTER1_2_COUNT                         1
#define MOD_SSPLITTER1_2_DEVICE                        "IC1"
#define MOD_SSPLITTER1_2_SINGLECTRLSPLIT2_ADDR         0
#define MOD_SSPLITTER1_2_SINGLECTRLSPLIT2_FIXPT        0x00800000
#define MOD_SSPLITTER1_2_SINGLECTRLSPLIT2_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SSPLITTER1_2_SINGLECTRLSPLIT2_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module S Splitter1_3 - Single Control Splitter*/
#define MOD_SSPLITTER1_3_COUNT                         1
#define MOD_SSPLITTER1_3_DEVICE                        "IC1"
#define MOD_SSPLITTER1_3_SINGLECTRLSPLIT3_ADDR         1
#define MOD_SSPLITTER1_3_SINGLECTRLSPLIT3_FIXPT        0x00800000
#define MOD_SSPLITTER1_3_SINGLECTRLSPLIT3_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SSPLITTER1_3_SINGLECTRLSPLIT3_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module Mg1 - Signal Merger*/
#define MOD_MG1_COUNT                                  1
#define MOD_MG1_DEVICE                                 "IC1"
#define MOD_MG1_SINGLECTRLMIXER19401_ADDR              2
#define MOD_MG1_SINGLECTRLMIXER19401_FIXPT             0x00400000
#define MOD_MG1_SINGLECTRLMIXER19401_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_MG1_SINGLECTRLMIXER19401_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1 - Limiter*/
#define MOD_LIMITER1_COUNT                             15
#define MOD_LIMITER1_DEVICE                            "IC1"
#define MOD_LIMITER1_ALG0_S1_ADDR                      3
#define MOD_LIMITER1_ALG0_S1_FIXPT                     0xFFFE2BE3
#define MOD_LIMITER1_ALG0_S1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER1_ALG0_S1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT1_ADDR                    4
#define MOD_LIMITER1_ALG0_INT1_FIXPT                   0x0022BE2B
#define MOD_LIMITER1_ALG0_INT1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER1_ALG0_INT1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S2_ADDR                      5
#define MOD_LIMITER1_ALG0_S2_FIXPT                     0xFFEAAAAB
#define MOD_LIMITER1_ALG0_S2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER1_ALG0_S2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT2_ADDR                    6
#define MOD_LIMITER1_ALG0_INT2_FIXPT                   0x006AAAAA
#define MOD_LIMITER1_ALG0_INT2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER1_ALG0_INT2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S3_ADDR                      7
#define MOD_LIMITER1_ALG0_S3_FIXPT                     0xFF9A69A7
#define MOD_LIMITER1_ALG0_S3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER1_ALG0_S3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT3_ADDR                    8
#define MOD_LIMITER1_ALG0_INT3_FIXPT                   0x00FDF7DF
#define MOD_LIMITER1_ALG0_INT3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER1_ALG0_INT3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_S4_ADDR                      9
#define MOD_LIMITER1_ALG0_S4_FIXPT                     0xF83C6C20
#define MOD_LIMITER1_ALG0_S4_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER1_ALG0_S4_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_INT4_ADDR                    10
#define MOD_LIMITER1_ALG0_INT4_FIXPT                   0x03F5AA22
#define MOD_LIMITER1_ALG0_INT4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER1_ALG0_INT4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C1_ADDR                      11
#define MOD_LIMITER1_ALG0_C1_FIXPT                     0x01800000
#define MOD_LIMITER1_ALG0_C1_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER1_ALG0_C1_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C2_ADDR                      12
#define MOD_LIMITER1_ALG0_C2_FIXPT                     0x01000000
#define MOD_LIMITER1_ALG0_C2_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER1_ALG0_C2_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_C3_ADDR                      13
#define MOD_LIMITER1_ALG0_C3_FIXPT                     0x00333333
#define MOD_LIMITER1_ALG0_C3_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER1_ALG0_C3_TYPE                      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_THRESHOLD_ADDR               14
#define MOD_LIMITER1_ALG0_THRESHOLD_FIXPT              0x00800000
#define MOD_LIMITER1_ALG0_THRESHOLD_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER1_ALG0_THRESHOLD_TYPE               SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_RMS_ADDR                     15
#define MOD_LIMITER1_ALG0_RMS_FIXPT                    0x00000192
#define MOD_LIMITER1_ALG0_RMS_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.79716733745583E-05)
#define MOD_LIMITER1_ALG0_RMS_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_DECAY_ADDR                   16
#define MOD_LIMITER1_ALG0_DECAY_FIXPT                  0x00000800
#define MOD_LIMITER1_ALG0_DECAY_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER1_ALG0_DECAY_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_ADDR         17
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_FIXPT        0x007FF000
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER1_ALG0_DECAYCOMPLEMENT_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1_2 - Limiter*/
#define MOD_LIMITER1_2_COUNT                           15
#define MOD_LIMITER1_2_DEVICE                          "IC1"
#define MOD_LIMITER1_2_ALG0_S1_ADDR                    18
#define MOD_LIMITER1_2_ALG0_S1_FIXPT                   0xFFFE2BE3
#define MOD_LIMITER1_2_ALG0_S1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER1_2_ALG0_S1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_INT1_ADDR                  19
#define MOD_LIMITER1_2_ALG0_INT1_FIXPT                 0x0022BE2B
#define MOD_LIMITER1_2_ALG0_INT1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER1_2_ALG0_INT1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_S2_ADDR                    20
#define MOD_LIMITER1_2_ALG0_S2_FIXPT                   0xFFEAAAAB
#define MOD_LIMITER1_2_ALG0_S2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER1_2_ALG0_S2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_INT2_ADDR                  21
#define MOD_LIMITER1_2_ALG0_INT2_FIXPT                 0x006AAAAA
#define MOD_LIMITER1_2_ALG0_INT2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER1_2_ALG0_INT2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_S3_ADDR                    22
#define MOD_LIMITER1_2_ALG0_S3_FIXPT                   0xFF9A69A7
#define MOD_LIMITER1_2_ALG0_S3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER1_2_ALG0_S3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_INT3_ADDR                  23
#define MOD_LIMITER1_2_ALG0_INT3_FIXPT                 0x00FDF7DF
#define MOD_LIMITER1_2_ALG0_INT3_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER1_2_ALG0_INT3_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_S4_ADDR                    24
#define MOD_LIMITER1_2_ALG0_S4_FIXPT                   0xF83C6C20
#define MOD_LIMITER1_2_ALG0_S4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER1_2_ALG0_S4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_INT4_ADDR                  25
#define MOD_LIMITER1_2_ALG0_INT4_FIXPT                 0x03F5AA22
#define MOD_LIMITER1_2_ALG0_INT4_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER1_2_ALG0_INT4_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_C1_ADDR                    26
#define MOD_LIMITER1_2_ALG0_C1_FIXPT                   0x01800000
#define MOD_LIMITER1_2_ALG0_C1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER1_2_ALG0_C1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_C2_ADDR                    27
#define MOD_LIMITER1_2_ALG0_C2_FIXPT                   0x01000000
#define MOD_LIMITER1_2_ALG0_C2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER1_2_ALG0_C2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_C3_ADDR                    28
#define MOD_LIMITER1_2_ALG0_C3_FIXPT                   0x00333333
#define MOD_LIMITER1_2_ALG0_C3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER1_2_ALG0_C3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_THRESHOLD_ADDR             29
#define MOD_LIMITER1_2_ALG0_THRESHOLD_FIXPT            0x00800000
#define MOD_LIMITER1_2_ALG0_THRESHOLD_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER1_2_ALG0_THRESHOLD_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_RMS_ADDR                   30
#define MOD_LIMITER1_2_ALG0_RMS_FIXPT                  0x00000192
#define MOD_LIMITER1_2_ALG0_RMS_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.79716733745583E-05)
#define MOD_LIMITER1_2_ALG0_RMS_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_DECAY_ADDR                 31
#define MOD_LIMITER1_2_ALG0_DECAY_FIXPT                0x00000800
#define MOD_LIMITER1_2_ALG0_DECAY_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER1_2_ALG0_DECAY_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_2_ALG0_DECAYCOMPLEMENT_ADDR       32
#define MOD_LIMITER1_2_ALG0_DECAYCOMPLEMENT_FIXPT      0x007FF000
#define MOD_LIMITER1_2_ALG0_DECAYCOMPLEMENT_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER1_2_ALG0_DECAYCOMPLEMENT_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module Limiter 1_3 - Limiter*/
#define MOD_LIMITER1_3_COUNT                           15
#define MOD_LIMITER1_3_DEVICE                          "IC1"
#define MOD_LIMITER1_3_ALG0_S1_ADDR                    33
#define MOD_LIMITER1_3_ALG0_S1_FIXPT                   0xFFFE2BE3
#define MOD_LIMITER1_3_ALG0_S1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.01428571428571)
#define MOD_LIMITER1_3_ALG0_S1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_INT1_ADDR                  34
#define MOD_LIMITER1_3_ALG0_INT1_FIXPT                 0x0022BE2B
#define MOD_LIMITER1_3_ALG0_INT1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.27142857142857)
#define MOD_LIMITER1_3_ALG0_INT1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_S2_ADDR                    35
#define MOD_LIMITER1_3_ALG0_S2_FIXPT                   0xFFEAAAAB
#define MOD_LIMITER1_3_ALG0_S2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.16666666666667)
#define MOD_LIMITER1_3_ALG0_S2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_INT2_ADDR                  36
#define MOD_LIMITER1_3_ALG0_INT2_FIXPT                 0x006AAAAA
#define MOD_LIMITER1_3_ALG0_INT2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.8333333333333)
#define MOD_LIMITER1_3_ALG0_INT2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_S3_ADDR                    37
#define MOD_LIMITER1_3_ALG0_S3_FIXPT                   0xFF9A69A7
#define MOD_LIMITER1_3_ALG0_S3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.79365079365079)
#define MOD_LIMITER1_3_ALG0_S3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_INT3_ADDR                  38
#define MOD_LIMITER1_3_ALG0_INT3_FIXPT                 0x00FDF7DF
#define MOD_LIMITER1_3_ALG0_INT3_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98412698412698)
#define MOD_LIMITER1_3_ALG0_INT3_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_S4_ADDR                    39
#define MOD_LIMITER1_3_ALG0_S4_FIXPT                   0xF83C6C20
#define MOD_LIMITER1_3_ALG0_S4_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-15.527950310559)
#define MOD_LIMITER1_3_ALG0_S4_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_INT4_ADDR                  40
#define MOD_LIMITER1_3_ALG0_INT4_FIXPT                 0x03F5AA22
#define MOD_LIMITER1_3_ALG0_INT4_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(7.91925465838509)
#define MOD_LIMITER1_3_ALG0_INT4_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_C1_ADDR                    41
#define MOD_LIMITER1_3_ALG0_C1_FIXPT                   0x01800000
#define MOD_LIMITER1_3_ALG0_C1_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3)
#define MOD_LIMITER1_3_ALG0_C1_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_C2_ADDR                    42
#define MOD_LIMITER1_3_ALG0_C2_FIXPT                   0x01000000
#define MOD_LIMITER1_3_ALG0_C2_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_LIMITER1_3_ALG0_C2_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_C3_ADDR                    43
#define MOD_LIMITER1_3_ALG0_C3_FIXPT                   0x00333333
#define MOD_LIMITER1_3_ALG0_C3_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.4)
#define MOD_LIMITER1_3_ALG0_C3_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_THRESHOLD_ADDR             44
#define MOD_LIMITER1_3_ALG0_THRESHOLD_FIXPT            0x00800000
#define MOD_LIMITER1_3_ALG0_THRESHOLD_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LIMITER1_3_ALG0_THRESHOLD_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_RMS_ADDR                   45
#define MOD_LIMITER1_3_ALG0_RMS_FIXPT                  0x00000192
#define MOD_LIMITER1_3_ALG0_RMS_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.79716733745583E-05)
#define MOD_LIMITER1_3_ALG0_RMS_TYPE                   SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_DECAY_ADDR                 46
#define MOD_LIMITER1_3_ALG0_DECAY_FIXPT                0x00000800
#define MOD_LIMITER1_3_ALG0_DECAY_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_LIMITER1_3_ALG0_DECAY_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LIMITER1_3_ALG0_DECAYCOMPLEMENT_ADDR       47
#define MOD_LIMITER1_3_ALG0_DECAYCOMPLEMENT_FIXPT      0x007FF000
#define MOD_LIMITER1_3_ALG0_DECAYCOMPLEMENT_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.99951171875)
#define MOD_LIMITER1_3_ALG0_DECAYCOMPLEMENT_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module S Splitter1 - Single Control Splitter*/
#define MOD_SSPLITTER1_COUNT                           1
#define MOD_SSPLITTER1_DEVICE                          "IC1"
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_ADDR           48
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_FIXPT          0x00800000
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_TYPE           SIGMASTUDIOTYPE_FIXPOINT

#endif
